import { Check, Sparkles, Target, Zap, Clock, Shield, BarChart3 } from 'lucide-react';
import { Button } from '../components/ui/button';

interface LandingPageProps {
  onGetStarted: () => void;
  onNavigate: (page: string) => void;
}

export function LandingPage({ onGetStarted, onNavigate }: LandingPageProps) {
  const features = [
    {
      icon: Target,
      title: 'Smart Subreddit Discovery',
      description: 'AI suggests the best subreddits for your app based on your project description',
    },
    {
      icon: Clock,
      title: 'Historical Scanning',
      description: 'Scan up to 90 days of Reddit history to find missed engagement opportunities',
    },
    {
      icon: Sparkles,
      title: 'AI-Generated Responses',
      description: 'Get contextual, authentic responses generated by GPT-4 for every mention',
    },
    {
      icon: Shield,
      title: 'Human Approval',
      description: 'Review and approve all responses before posting to maintain authenticity',
    },
    {
      icon: BarChart3,
      title: 'Unified Feed',
      description: 'All mentions, DMs, comments, and posts in one sortable, filterable feed',
    },
    {
      icon: Zap,
      title: 'Custom AI Personas',
      description: 'Configure your AI response style to match your brand voice perfectly',
    },
  ];

  const stats = [
    { value: '90 days', label: 'Historical Scanning' },
    { value: 'Unlimited', label: 'Projects (Pro)' },
    { value: 'AI-Powered', label: 'Smart Responses' },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-teal-50 via-emerald-50 to-cyan-50">
      {/* Hero Section */}
      <section className="pt-32 pb-20 px-4 sm:px-6 lg:px-8">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center space-y-8">
            <div className="inline-flex items-center gap-2 px-4 py-2 bg-white/60 backdrop-blur-sm rounded-full border border-teal-200/50">
              <Sparkles className="h-4 w-4 text-teal-600" />
              <span className="text-sm text-teal-900">AI-Powered Reddit Engagement</span>
            </div>
            
            <h1 className="text-5xl sm:text-6xl lg:text-7xl max-w-4xl mx-auto bg-gradient-to-r from-teal-600 via-emerald-600 to-cyan-600 bg-clip-text text-transparent leading-tight">
              Connect with Customers Where They Talk
            </h1>
            
            <p className="text-xl sm:text-2xl text-gray-600 max-w-3xl mx-auto">
              PubHub helps app developers monitor Reddit, discover engagement opportunities, 
              and craft authentic AI-powered responses
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center items-center pt-4">
              <Button
                onClick={onGetStarted}
                size="lg"
                className="text-lg px-8 py-6 bg-gradient-to-r from-teal-600 via-emerald-600 to-cyan-600 text-white hover:opacity-90"
              >
                Get Started Free
              </Button>
              <Button
                onClick={() => onNavigate('pricing')}
                size="lg"
                variant="outline"
                className="text-lg px-8 py-6 border-teal-300 hover:bg-teal-50"
              >
                View Pricing
              </Button>
            </div>

            {/* Stats */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-8 pt-12 max-w-3xl mx-auto">
              {stats.map((stat, index) => (
                <div key={index} className="text-center">
                  <div className="text-3xl sm:text-4xl bg-gradient-to-r from-teal-600 via-emerald-600 to-cyan-600 bg-clip-text text-transparent">
                    {stat.value}
                  </div>
                  <div className="text-sm text-gray-600 mt-1">{stat.label}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 bg-white">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center space-y-4 mb-16">
            <h2 className="text-4xl sm:text-5xl bg-gradient-to-r from-teal-600 via-emerald-600 to-cyan-600 bg-clip-text text-transparent">
              Everything You Need
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Powerful features to help you engage authentically with your Reddit community
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <div
                key={index}
                className="p-6 rounded-2xl bg-gradient-to-br from-teal-50 to-cyan-50 border border-teal-200/50 hover:shadow-lg transition-shadow"
              >
                <div className="w-12 h-12 rounded-xl bg-gradient-to-r from-teal-600 via-emerald-600 to-cyan-600 flex items-center justify-center mb-4">
                  <feature.icon className="h-6 w-6 text-white" />
                </div>
                <h3 className="text-xl text-gray-900 mb-2">{feature.title}</h3>
                <p className="text-gray-600">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="py-20 px-4 sm:px-6 lg:px-8">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center space-y-4 mb-16">
            <h2 className="text-4xl sm:text-5xl bg-gradient-to-r from-teal-600 via-emerald-600 to-cyan-600 bg-clip-text text-transparent">
              How It Works
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Start engaging with your community in minutes
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            {[
              {
                step: '1',
                title: 'Create Project',
                description: 'Describe your app and target audience',
              },
              {
                step: '2',
                title: 'Get AI Suggestions',
                description: 'Receive relevant subreddit recommendations',
              },
              {
                step: '3',
                title: 'Monitor Feed',
                description: 'Track mentions, DMs, and opportunities',
              },
              {
                step: '4',
                title: 'Engage Authentically',
                description: 'Review AI responses and post with confidence',
              },
            ].map((item, index) => (
              <div key={index} className="text-center space-y-4">
                <div className="w-16 h-16 rounded-full bg-gradient-to-r from-teal-600 via-emerald-600 to-cyan-600 flex items-center justify-center text-2xl text-white mx-auto">
                  {item.step}
                </div>
                <h3 className="text-xl text-gray-900">{item.title}</h3>
                <p className="text-gray-600">{item.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 bg-gradient-to-r from-teal-600 via-emerald-600 to-cyan-600">
        <div className="container mx-auto max-w-4xl text-center space-y-8">
          <h2 className="text-4xl sm:text-5xl text-white">
            Ready to Connect with Your Community?
          </h2>
          <p className="text-xl text-white/90">
            Join app developers who are building authentic relationships on Reddit
          </p>
          <Button
            onClick={onGetStarted}
            size="lg"
            className="text-lg px-8 py-6 bg-white text-teal-600 hover:bg-gray-50"
          >
            Start Free Today
          </Button>
          <p className="text-sm text-white/70">No credit card required • Free tier available</p>
        </div>
      </section>
    </div>
  );
}
