/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = (import.meta.env?.VITE_SUPABASE_PROJECT_ID as string | undefined) || "vcdfzxjlahsajulpxzsn"
export const publicAnonKey = (import.meta.env?.VITE_SUPABASE_ANON_KEY as string | undefined) || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjZGZ6eGpsYWhzYWp1bHB4enNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3Njk3NjYsImV4cCI6MjA3NTM0NTc2Nn0.V6Q9vuwgjBg7QQFnBnet4eEnOafk5_mDOtWe9Upy0Kw"